### ISSUE TITLE
Slow to open after compile

### ISSUE THREAD

**Issue by raccoon-id** [armory3d/armortools#1594]
Hi all.

I decide to try AP, so I've compiled the git version instead of get the "paid one".

BUT, after compile the .exe file under my main machine, AP takes over 20 seconds to load. I've copied the same .exe files (already compiled) to another computer with a 1060 6 GB and it takes less than 0.5 seconds to open and about 1 second in my notebook with Ryzen processor and APU (5XXX series).

So, how can I "track the problem".

I've uninstalled Visual Studio and etc after compile the program, the second PC is a fresh Windows install with no VS stuff and no .NET specific things, there is some software dependencies needed to install?

Windows 11 22H2 OS Comp. 22621.1848 Windows Feature Experience Pack 1000.22642.1000.0
DX11 (DX12 have some visual glitches).
Ryzen 9 3900X
Radeon 790XTX
32 GB RAM 3200 MHZ non QVL
WD Black NVME (don't remember the rest).

**Comment by luboslenco** [comment]
Sorry but have no clue why it takes so long on that machine while working normally on another. :( Only idea is to maybe check some scanning / antivirus software if present, updating graphics drivers etc.

If some dependency would be missing ArmorPaint should not start at all, but since it still starts after 20 seconds it looks like something is stalling it.

You might also try running it directly from Visual Studio and try to investigate what is going on during the launch.
