### ISSUE TITLE
wave texture works incorrectly with color ramp

### ISSUE THREAD

**Issue by soundsbeard** [armory3d/armortools#1603]
**ArmorPaint version:**
v0.9 (2023-07-13) - 4d0b2f5

**OS/device including version:**
non-DXR i guess
all specs: https://controlc.com/a4437c7a

**Issue description:**
when wave texture is put through the color ramp it looks distorted

in this video i show 2 procedural textures: musgrave and wave.
at first i put both of them through bright/contrast node with default values.
both nodes look unchanged.

then i put both of them through the classic 'black to white' color ramp (color stop with index 0 is full black with position 0, color stop with index 1 is pure white with position 1) 
in that case musgrave remains unchanged, while wave is distorted.

https://github.com/armory3d/armortools/assets/16347074/5eb13d54-3955-4bd9-992f-8af624413982

also, i wonder, why is this ticket closed: https://github.com/armory3d/armortools/issues/1085 ? 
color ramp looks so unintuitive.

**Steps to reproduce:**
- add wave texture node
- add color ramp node
- put wave texture into color ramp
- but the output into base color

**Comment by luboslenco** [comment]
> also, i wonder, why is this ticket closed: https://github.com/armory3d/armortools/issues/1085 ?

It is not meant to be resolved, I just group the tickets together at:
https://github.com/armory3d/armortools/issues/36

If you examine that issue you can see the links to all the node tickets there. Sorry the ticket grouping is a bit aggressive, but otherwise it would just explode and be unmanageable for me. It's already tough to keep up.

Will resolve this one as well, linking together with https://github.com/armory3d/armortools/issues/36. Thanks for the reports.
