### ISSUE TITLE
Cannot open: GLIBC_2.36 not found

### ISSUE THREAD

**Issue by Airyzz** [armory3d/armortools#1689]
**ArmorPaint version:**

10alpha_linux64

**OS/device including version:**

Pop!_OS 22.04 LTS, NVIDIA 3070

**Issue description:**

Cannot open the app, says:
```
./ArmorPaint: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.36' not found (required by ./ArmorPaint)
```

I am able to open 0.9 just fine however

**Comment by twinkelmann** [comment]
I have the exact same issue, with the prebuilt version, on Pop!_OS 22.04 LTS, NVIDIA GTX 980Ti.
0.9 Also works for me.

**Comment by RandallCurtis** [comment]
Same here on Mint 21.3 (also Ubuntu 22.04 based). ArmorPaint 0.9 launches but has a 2D viewport bug which was fixed in 1.0. Ubuntu 22.04 is an LTS version packaged with glibc 2.35 so it seems like the only solution would be to self compile. I imagine that Ubuntu LTS is fairly common among Linux users so would it be possible for future pre-builds to be 22.04 compatible or maybe an AppImage?

**Comment by t4paN** [comment]
Same issue here on Mint 21.3.

**Comment by dimension128** [comment]
If GLIBC_2.36 isn't actually required, can it be changed to at least 2.35? I understand both were released in 2022, however some distros (including LTS releases such as Mint 21.3 which will be supported until 2027) are still using 2.35.
I just bought this through itch, and I can't use it.

**Comment by luboslenco** [comment]
Should be resolved now in 10alpha_linux64, sorry it took a while. 0.9 might still be more stable.
