### ISSUE TITLE
GLIBC_2.38' not found on Ubuntu 22.04

### ISSUE THREAD

**Issue by Ciaxeres** [armory3d/armortools#1721]
I followed the path for installation, but always returns the same error:

Kinc/Tools/linux_x64/kmake: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.38' not found (required by Kinc/Tools/linux_x64/kmake)

**Comment by AllenOliver** [comment]
Same issue here. Ever get a fix?

**Comment by RandallCurtis** [comment]
Similar to #1689
Ubuntu 22.04 based installations are GLibC 2.35
Compiling from source worked for me on Mint 21.3 so unless future pre-builds are compiled with GLibC <= 2.35 that seems like the only option at the moment

**Comment by t4paN** [comment]
> Similar to #1689 Ubuntu 22.04 based installations are GLibC 2.35 Compiling from source worked for me on Mint 21.3 so unless future pre-builds are compiled with GLibC <= 2.35 that seems like the only option at the moment

I tried to compile the latest version and it still gave me the glibc error,

**Comment by oliiix** [comment]
Yeah also Ubuntu / Pop OS here with glibc 2.35. Hilarious, there i wanna try before buy but you make it simply impossible.... Seriously what logic is that behavior based on that if you want it free you have to build it yourself, otherwise buy it. Well I'd like to test it so I can decide if i wanna buy it, but that is of course not possible because you make it glibc 2.38 dependable... You'd rather make a demo version pre-compiled so we can actually properly test it.

**Comment by luboslenco** [comment]
There may be other issues still but at least the kmake glibc version should be lowered now (built on Ubuntu 20.04).

> guess that was the last time

I hope so, bye!
